
############################################################ source files.
SUBDIRS :=./src
INC     +=./inc
INC     += $(PROJ_ROOT)/release/include

OUTPUT_DIR := $(DB_OUT_PATH)/obj/

############################################################ depnedent header files.
include $(DB_BUILD_TOP)/compile.mk
all: gen_obj
clean: clean_files
